### ISSUE TITLE
ES실행하고 Kibana실행했을때 연결끊김 (while handling client http traffic, closing connection)

### ISSUE THREAD

**Issue by restato** [restato/small-business#6]
아래 메시지가 주기적으로 나타난다. kibana가 처음에 실행이 되고 접속이 되지만,
이후에 접속이 접속느리고, dashboard를 누르면 페이지가 열리지 않는다.
이 문제는 서울특별시 데이터를 넣은 이후에 생긴 문제 자원문제일까?
방금 dashboard가 열렸는데 데이터 로딩이 상당히 느리다.

```
[2019-01-10T23:58:35,413][WARN ][o.e.x.s.t.n.SecurityNetty4HttpServerTransport] [o37CXGK] caught exception while handling client http traffic, closing connection [id: 0xf8de002c, L:/127.0.0.1:9200 - R:/127.0.0.1:48854]
java.io.IOException: 연결이 상대편에 의해 끊어짐
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:?]
        at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128) ~[netty-buffer-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347) ~[netty-transport-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-common-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by restato** [comment]
전체 사용중인 메모리의 양이 많아. 
불필요한 작업 종료하니 정상적으로 동작
